In [1]:
import torch
import ttnn


2026-02-09 09:40:20.131 | DEBUG    | ttnn:<module>:77 - Initial ttnn.CONFIG:
Config{cache_path=/root/.cache/ttnn,model_cache_path=/root/.cache/ttnn/models,tmp_dir=/tmp/ttnn,enable_model_cache=false,enable_fast_runtime_mode=true,throw_exception_on_fallback=false,enable_logging=false,enable_graph_report=false,enable_detailed_buffer_report=false,enable_detailed_tensor_report=false,enable_comparison_mode=false,comparison_mode_should_raise_exception=false,comparison_mode_pcc=0.9999,root_report_path=generated/ttnn/reports,report_name=std::nullopt,std::nullopt}


In [2]:
ttnn.open_device(device_id=0)

2026-02-09 09:40:20.254 | info     |             UMD | Starting topology discovery. (topology_discovery.cpp:69)
2026-02-09 09:40:20.645 | info     |             UMD | Established firmware bundle version: 19.1.0 (topology_discovery.cpp:369)
2026-02-09 09:40:20.645 | info     |             UMD | Established ETH FW version: 1.7.0 (topology_discovery_blackhole.cpp:305)
2026-02-09 09:40:20.645 | info     |             UMD | Completed topology discovery. (topology_discovery.cpp:73)
2026-02-09 09:40:20.864 | info     |          Device | Opening user mode device driver (tt_cluster.cpp:209)
2026-02-09 09:40:20.864 | info     |             UMD | Starting topology discovery. (topology_discovery.cpp:69)
2026-02-09 09:40:21.256 | info     |             UMD | Established firmware bundle version: 19.1.0 (topology_discovery.cpp:369)
2026-02-09 09:40:21.256 | info     |             UMD | Established ETH FW version: 1.7.0 (topology_discovery_blackhole.cpp:305)
2026-02-09 09:40:21.256 | info     |       

MeshDevice(1x1 grid, 1 devices)

In [ ]:
prefill_k = ttnn.load_tensor("/tt-metal/models/experimental/indusproject/dumps/prefill_k_0.tensorbin")
prefill_k = ttnn.to_torch(prefill_k)
print(prefill_k.shape)

prefill_q = ttnn.load_tensor("/tt-metal/models/experimental/indusproject/dumps/prefill_q_0.tensorbin")
prefill_q = ttnn.to_torch(prefill_q)
print(prefill_q.shape)

prefill_v = ttnn.load_tensor("/tt-metal/models/experimental/indusproject/dumps/prefill_v_0.tensorbin")
prefill_v = ttnn.to_torch(prefill_v)
print(prefill_v.shape)

torch.Size([1, 32, 16, 64])
torch.Size([1, 32, 16, 64])
torch.Size([1, 32, 16, 64])


In [57]:
only_prefill_og_k = ttnn.load_tensor("/tt-metal/models/experimental/indusproject/dumps_prefill/prefill_k_0.tensorbin")
only_prefill_og_k = ttnn.to_torch(only_prefill_og_k)
print(only_prefill_og_k.shape)

only_prefill_og_q = ttnn.load_tensor("/tt-metal/models/experimental/indusproject/dumps_prefill/prefill_q_0.tensorbin")
only_prefill_og_q = ttnn.to_torch(only_prefill_og_q)
print(only_prefill_og_q.shape)

only_prefill_og_v = ttnn.load_tensor("/tt-metal/models/experimental/indusproject/dumps_prefill/prefill_v_0.tensorbin")
only_prefill_og_v = ttnn.to_torch(only_prefill_og_v)
print(only_prefill_og_v.shape)

torch.Size([1, 32, 25, 64])
torch.Size([1, 32, 25, 64])
torch.Size([1, 32, 25, 64])


In [38]:
prefill_v[:, :, -1, :].shape

torch.Size([1, 32, 64])

In [39]:
only_prefill_v[:, :, 15, :].shape

torch.Size([1, 32, 64])

In [40]:
k_1 = prefill_v[:, :, -1, :]
k_2 = only_prefill_v[:, :, 15, :]

k = k_1-k_2
f = (k == 0).all()

print(f)

tensor(True)


In [21]:
decode_k = ttnn.load_tensor("/tt-metal/models/experimental/indusproject/dumps/decode_k_16.tensorbin")
decode_k = ttnn.to_torch(decode_k)
print(decode_k.shape)

decode_q = ttnn.load_tensor("/tt-metal/models/experimental/indusproject/dumps/decode_q_16.tensorbin")
decode_q = ttnn.to_torch(decode_q)
print(decode_q.shape)

decode_v = ttnn.load_tensor("/tt-metal/models/experimental/indusproject/dumps/decode_v_16.tensorbin")
decode_v = ttnn.to_torch(decode_v)
print(decode_v.shape)

torch.Size([1, 1, 32, 64])
torch.Size([1, 1, 32, 64])
torch.Size([1, 1, 32, 64])


In [41]:
only_prefill_v[:, :, 16, :].shape

torch.Size([1, 32, 64])

In [49]:
k_1 = decode_k
k_1 = k_1.permute(0, 2, 1, 3)
k_1 = k_1[:, :, -1, :]

k_2 = only_prefill_k[:, :, 16, :]

k = k_1-k_2
f = (k == 0).all()

print(f)

tensor(False)


In [3]:
decode_k = ttnn.load_tensor("/tt-metal/models/experimental/indusproject/layer_1_run_1/dumps/decode_k_16.tensorbin")
decode_k = ttnn.to_torch(decode_k)
print(decode_k.shape)

decode_q = ttnn.load_tensor("/tt-metal/models/experimental/indusproject/layer_1_run_1/dumps/decode_q_16.tensorbin")
decode_q = ttnn.to_torch(decode_q)
print(decode_q.shape)

decode_v = ttnn.load_tensor("/tt-metal/models/experimental/indusproject/layer_1_run_1/dumps/decode_v_16.tensorbin")
decode_v = ttnn.to_torch(decode_v)
print(decode_v.shape)

torch.Size([1, 1, 32, 64])
torch.Size([1, 1, 32, 64])
torch.Size([1, 1, 32, 64])


In [4]:
only_prefill_k = ttnn.load_tensor("/tt-metal/models/experimental/indusproject/layer_1_run_1/dumps_prefill/prefill_k_0.tensorbin")
only_prefill_k = ttnn.to_torch(only_prefill_k)
print(only_prefill_k.shape)

only_prefill_q = ttnn.load_tensor("/tt-metal/models/experimental/indusproject/layer_1_run_1/dumps_prefill/prefill_q_0.tensorbin")
only_prefill_q = ttnn.to_torch(only_prefill_q)
print(only_prefill_q.shape)

only_prefill_v = ttnn.load_tensor("/tt-metal/models/experimental/indusproject/layer_1_run_1/dumps_prefill/prefill_v_0.tensorbin")
only_prefill_v = ttnn.to_torch(only_prefill_v)
print(only_prefill_v.shape)

torch.Size([1, 32, 17, 64])
torch.Size([1, 32, 17, 64])
torch.Size([1, 32, 17, 64])


In [5]:
k1= decode_k[:, -1, :, :]

In [6]:
k2 = only_prefill_k[:, :, -1, :]

In [7]:
k = k2 - k1

In [11]:
k[:, 1]

tensor([[-0.2500, -0.1875,  0.0625, -0.0625, -0.5781,  0.0312, -0.0625, -0.0938,
          0.0625, -0.0625, -0.1250,  0.0625,  0.0625, -0.0625, -0.0625,  0.0000,
         -0.1250,  0.3750,  0.0000, -0.0625, -0.1250,  0.0000, -0.3750, -0.0625,
         -0.3125, -0.0625,  0.1250,  0.2188, -0.0625,  0.0000,  0.1250,  0.0625,
          0.0625,  0.3750, -0.0625,  0.3750,  0.0859, -0.0625,  0.0000,  0.0938,
          0.0625,  0.1250, -0.1875, -0.4004, -0.0625,  0.0625, -0.0625,  0.2812,
          0.0000, -0.4062,  0.1250,  0.0000, -0.2188,  0.5977, -0.1562, -0.0312,
          0.1250, -0.0625,  0.0000,  0.0625, -0.1250,  0.0000,  0.0625,  0.0625]],
       dtype=torch.bfloat16)

In [9]:
k_1 = decode_k
k_1 = k_1[:, -1, :]

k_2 = only_prefill_k[:, :, -1, :]

k = k_1-k_2
f = (k == 0).all()

print(f)

tensor(False)


In [ ]:
## without sharded to interleave and reshape before create heads decode
# in the forward of first layer

# keys.shape
# Shape([1, 32, 1024, 64])
# k.shape
# Shape([1, 1, 32, 64])
# keys.padded_shape
# Shape([1, 32, 1024, 64])
# k.padded_shape
# Shape([1, 1, 32, 64])

# inforward of second layer

# keys.shape
# Shape([1, 32, 1024, 64])
# k.shape
# Shape([1, 32, 32, 64])
# keys.padded_shape
# Shape([1, 32, 1024, 64])
# k.padded_shape
# Shape([1, 32, 32, 64])

In [ ]:
## with sharded to interleave and reshape before create heads decode
# in the forward of first layer

# keys.shape
# Shape([1, 32, 1024, 64])
# k.shape
# Shape([1, 1, 32, 64])
# keys.padded_shape
# Shape([1, 32, 1024, 64])
# k.padded_shape
# Shape([1, 1, 32, 64])

# inforward of second layer

# keys.shape
# Shape([1, 32, 1024, 64])
# k.shape
# Shape([1, 1, 32, 64])
# keys.padded_shape
# Shape([1, 32, 1024, 64])
# k.padded_shape
# Shape([1, 1, 32, 64])


In [5]:
only_prefill_emebd= ttnn.load_tensor("/tt-metal/models/experimental/indusproject/embed_layer_1/dumps_prefill/prefill_embed_0.tensorbin")
only_prefill_emebd = ttnn.to_torch(only_prefill_emebd)

In [6]:
only_prefill_emebd.shape

torch.Size([1, 1, 17, 6144])

In [10]:
only_prefill_emebd[:, :, 16, :]

tensor([[[-0.6406, -0.2773, -0.1953,  ...,  0.0057,  0.0034, -0.0505]]],
       dtype=torch.bfloat16)

In [8]:
decode_emebed= ttnn.load_tensor("/tt-metal/models/experimental/indusproject/embed_layer_1/dumps/decode_embed_16.tensorbin")
decode_emebed = ttnn.to_torch(decode_emebed)

In [11]:
decode_emebed

tensor([[[[-0.6406, -0.2773, -0.1953,  ...,  0.0057,  0.0034, -0.0505]]]],
       dtype=torch.bfloat16)

In [9]:
decode_emebed.shape

torch.Size([1, 1, 1, 6144])