In [1]:
import torch

In [8]:
a1 = torch.load('attn_mask_1.pt')

In [9]:
a1.shape

torch.Size([2, 1, 32, 32])

In [12]:
a1[1, 0, 11]

tensor([    0.,     0.,     0.,     0.,     0.,     0.,     0.,     0.,     0.,
            0.,     0.,     0., -9984., -9984., -9984., -9984., -9984., -9984.,
        -9984., -9984., -9984., -9984., -9984., -9984., -9984., -9984., -9984.,
        -9984., -9984., -9984., -9984., -9984.], dtype=torch.bfloat16)

In [3]:
a = torch.load('attn_mask.pt')

In [5]:
a.shape

torch.Size([2, 1, 32, 32])

In [12]:
z = (a[1, 0] == 0).sum().item()

In [13]:
z

528

In [9]:
a[0, 0].shape


torch.Size([32, 32])

In [22]:
a[1, 0, 0]

tensor([    0., -9984., -9984., -9984., -9984., -9984., -9984., -9984., -9984.,
        -9984., -9984., -9984., -9984., -9984., -9984., -9984., -9984., -9984.,
        -9984., -9984., -9984., -9984., -9984., -9984., -9984., -9984., -9984.,
        -9984., -9984., -9984., -9984., -9984.], dtype=torch.bfloat16)

In [23]:
b = torch.load('pad_mask.pt')

In [24]:
b.shape

torch.Size([2, 1, 1, 32])

In [31]:
y = (b[0, 0, 0] == 0).sum().item()

In [36]:
b[0, 0, 0]

tensor([    0.,     0.,     0.,     0.,     0.,     0.,     0.,     0., -9984.,
            0.,     0., -9984., -9984., -9984., -9984., -9984., -9984., -9984.,
        -9984., -9984., -9984., -9984., -9984., -9984., -9984., -9984., -9984.,
        -9984., -9984., -9984., -9984., -9984.], dtype=torch.bfloat16)

In [32]:
y

10

In [33]:
c = torch.load('final_mask.pt')

In [34]:
c.shape

torch.Size([2, 1, 32, 32])

In [44]:
c[0, 0, 25]

tensor([     0.,      0.,      0.,      0.,      0.,      0.,      0.,      0.,
         -9984.,      0.,      0.,  -9984.,  -9984.,  -9984.,  -9984.,  -9984.,
         -9984.,  -9984.,  -9984.,  -9984.,  -9984.,  -9984.,  -9984.,  -9984.,
         -9984.,  -9984., -19968., -19968., -19968., -19968., -19968., -19968.],
       dtype=torch.bfloat16)

In [42]:
a[0, 0, 25]


tensor([    0.,     0.,     0.,     0.,     0.,     0.,     0.,     0.,     0.,
            0.,     0.,     0.,     0.,     0.,     0.,     0.,     0.,     0.,
            0.,     0.,     0.,     0.,     0.,     0.,     0.,     0., -9984.,
        -9984., -9984., -9984., -9984., -9984.], dtype=torch.bfloat16)

In [51]:
b.shape

torch.Size([2, 1, 1, 32])

In [52]:
b[0, 0, 0]

tensor([    0.,     0.,     0.,     0.,     0.,     0.,     0.,     0., -9984.,
            0.,     0., -9984., -9984., -9984., -9984., -9984., -9984., -9984.,
        -9984., -9984., -9984., -9984., -9984., -9984., -9984., -9984., -9984.,
        -9984., -9984., -9984., -9984., -9984.], dtype=torch.bfloat16)